services:
  app:
      build:
        context: .
        dockerfile: ./Dockerfile
      restart: on-failure
      cpu_count: 22
      volumes:
        - '.:/go/src/gocv.io/x/gocv/'
      entrypoint: "sleep infinity"
      develop:
        watch:
          - action: sync
            target: ./
            path: main.go